DROP TABLE IF EXISTS PROD_CATEGORY CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS INGREDIENT_REF CASCADE;
DROP TABLE IF EXISTS TACO_ORDER CASCADE;
DROP TABLE IF EXISTS INGREDIENT CASCADE;
DROP TABLE IF EXISTS TACO CASCADE;

CREATE TABLE IF NOT EXISTS PROD_CATEGORY (
    ID                 BIGSERIAL NOT NULL,
    NAME               VARCHAR (250) NOT NULL UNIQUE ,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID                 BIGSERIAL NOT NULL UNIQUE,
    NAME               VARCHAR (250) NOT NULL,
    SHORT_DESC         VARCHAR (2500) NOT NULL,
    DESCRIPTION        VARCHAR (10000) NOT NULL,
    CATEGORY_ID        INTEGER NOT NULL REFERENCES PROD_CATEGORY (ID),
    PRICE              NUMERIC (10, 2),
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS TACO_ORDER (
   ID                  BIGSERIAL NOT NULL,
   DELIVERY_NAME       VARCHAR (50) NOT NULL,
   DELIVERY_STREET     VARCHAR (50) NOT NULL,
   DELIVERY_CITY       VARCHAR (50) NOT NULL,
   DELIVERY_STATE      VARCHAR (2) NOT NULL,
   DELIVERY_ZIP        VARCHAR (10) NOT NULL,
   CC_NUMBER           VARCHAR (16) NOT NULL,
   CC_EXPIRATION       VARCHAR (5) NOT NULL,
   CC_CVV              VARCHAR (3) NOT NULL,
   PLACED_AT           TIMESTAMP NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TACO
(
   ID                 BIGSERIAL NOT NULL ,
   NAME               VARCHAR (50) NOT NULL,
   TACO_ORDER         INTEGER NOT NULL,
   TACO_ORDER_KEY     INTEGER NOT NULL,
   CREATED_AT         TIMESTAMP NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS INGREDIENT
(
   ID             VARCHAR (4) NOT NULL UNIQUE,
   NAME           VARCHAR (25) NOT NULL,
   TYPE           VARCHAR (10) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS INGREDIENT_REF
(
   INGREDIENT         VARCHAR (4) NOT NULL REFERENCES INGREDIENT (ID),
   TACO               BIGSERIAL NOT NULL REFERENCES TACO_ORDER (ID),
   TACO_KEY           INTEGER NOT NULL,
   PRIMARY KEY (INGREDIENT, TACO)
);

